/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Card: typeof import('primevue/card')['default']
    Divider: typeof import('primevue/divider')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    OtherProjectsByMe: typeof import('./src/components/projects/details/OtherProjectsByMe.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Project: typeof import('./src/components/projects/details/Project.vue')['default']
    ProjectBuildDetails: typeof import('./src/components/projects/details/ProjectBuildDetails.vue')['default']
    ProjectDescription: typeof import('./src/components/projects/details/ProjectDescription.vue')['default']
    ProjectDetail: typeof import('./src/components/projects/details/ProjectDetail.vue')['default']
    ProjectImages: typeof import('./src/components/projects/details/ProjectImages.vue')['default']
    ProjectProgress: typeof import('./src/components/projects/details/ProjectProgress.vue')['default']
    ProjectResults: typeof import('./src/components/projects/ProjectResults.vue')['default']
    ProjectSearch: typeof import('./src/components/projects/ProjectSearch.vue')['default']
    ProjectSearchCard: typeof import('./src/components/projects/ProjectSearchCard.vue')['default']
  }
}
