/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProjectResults: typeof import('./src/components/projects/ProjectResults.vue')['default']
    ProjectSearch: typeof import('./src/components/projects/ProjectSearch.vue')['default']
    ProjectSearchCard: typeof import('./src/components/projects/ProjectSearchCard.vue')['default']
  }
}
